Release notes updated
fortinet-fortisoar/widget-record-distribution pull request #23
Opened 2024-08-23 07:53 UTC by cs-yoges-chauriwar

#### Descriptions:
_Add PR descriptions here_

#### Fix:
_Add fix/changes here_

2024-08-26 14:25 UTC, cs-abhishek-shukla requested changes

2024-08-26 14:25 UTC, cs-abhishek-shukla commented on widget/release_notes.md
> +- Internationalization Support added for Japanese, Korean, and Simplified Chinese languages.
Added Internationalization support for Japanese, Korean, and Simplified Chinese languages.

2024-08-26 14:25 UTC, cs-abhishek-shukla commented on widget/release_notes.md
> +- Widget Filter retained with grid filter on module listing page, when redirected from the Widget through 'View All Records' option.
When users return to the records list after viewing a record in detail, the filter conditions they applied are now retained. Previously, returning to the records list cleared the filter conditions applied through the widget's *View All Records* option.

2024-08-27 05:01 UTC, cs-yoges-chauriwar commented on widget/release_notes.md
> +- Widget Filter retained with grid filter on module listing page, when redirected from the Widget through 'View All Records' option.
I think we should keep it like this,

When users return to the records list after viewing a record in detail, the additional grid filter conditions they applied are retained. Previously, returning to the records list widget's View All Records option filter was applied, but the additional grid filter conditions were cleared.

2024-08-27 07:16 UTC, cs-yoges-chauriwar commented on widget/release_notes.md
> +- Widget Filter retained with grid filter on module listing page, when redirected from the Widget through 'View All Records' option.
Done

2024-08-27 07:16 UTC, cs-yoges-chauriwar commented on widget/release_notes.md
> +- Internationalization Support added for Japanese, Korean, and Simplified Chinese languages.
Done

2024-08-27 09:14 UTC, cs-suyog-jinturkar approved these changes

2024-08-27 09:14 UTC, merged